### ISSUE TITLE
AGAL vs GLSL

### ISSUE THREAD

**Issue by jcyuan** [awayjs/stage#3]
use agal to write shader is really painful, why awayjs still uses it as the shading language?

**Comment by rob-bateman** [comment]
AGAL is not something we've stuck with out of choice, more necessity

Its something we would certainly like to replace at some point, but because of the way AwayJS constructs shaders, its not just as simple as replacing AGAL code with GLSL.

One solution we've been working towards is being able to swap out the AGAL-based materials in the materials module with an alternative materials library. We're close to enabling this bar a few minor dependencies left in scene and parsers, however you will also lose a lot of material-based functionality as a side effect of doing this, such as the animators

If you have some ideas for other steps we could take that would allow us to write GLSL code in place of AGAL while keeping our shader model intact, do let us know
